#!/usr/bin/env bash

set -x
set -e

mkdir -p _test_accounts_cli
pushd _test_accounts_cli

../scripts/setup_config_file.sh

# Create a keyfile from a private key and check the address
export HISTCONTROL=ignorespace
 echo '6173646661647366616473666173646671776572717765727177657271776572' > test_key.priv
rm -f test_key.key
aut account import-private-key --keyfile test_key.key --password '' test_key.priv > test_key_out
test_addr=`grep -oe '0x[0-9A-Za-z]\+' test_key_out`
if ! [ "${test_addr}" == "0x1e9Ee7293bc304A10a0b33D0FCCBDFF78463bE5c" ] ; then
   echo Private key generated wrong address
   exit 1
fi

# Create a keyfile from a private key (using stdin) and check the address
rm -f test_key.key
echo '6173646661647366616473666173646671776572717765727177657271776572' | \
    aut account import-private-key --keyfile test_key.key --password '' - > test_key_out
test_addr=`grep -oe '0x[0-9A-Za-z]\+' test_key_out`
if ! [ "${test_addr}" == "0x1e9Ee7293bc304A10a0b33D0FCCBDFF78463bE5c" ] ; then
   echo Private key generated wrong address
   exit 1
fi

# Create from private key to default file name
mkdir -p test_keystore
rm -f test_keystore/*
aut account import-private-key --keystore test_keystore --password '' test_key.priv > test_key_out
[ "1" == `ls test_keystore/*1e9ee7293bc304a10a0b33d0fccbdff78463be5c | wc -l` ]

# Create from private key to default file name and keystore
mv .autrc .autrc.bak
rm  -vf ~/.autonity/keystore/*1e9ee7293bc304a10a0b33d0fccbdff78463be5c
aut account import-private-key --password '' test_key.priv > test_key_out
[ "1" == `ls ~/.autonity/keystore/*1e9ee7293bc304a10a0b33d0fccbdff78463be5c | wc -l` ]
mv .autrc.bak .autrc

# Query commands
aut account list
aut account info
aut account info --keyfile keystore/bob.key
aut account balance

# Create new key.  Use --show-password to allow stdin to be piped to
# the password prompts.
rm -f keystore/dave.key
aut account new --keyfile keystore/dave.key --password ''
(aut account new --keyfile keystore/dave.key --password '') && (
    echo "ERROR: account new succeeded with existing file"; exit 1)

# Create account with entropy as file, and via stdin
rm -f keystore/dave_entropy_*.key
echo "entropy" | aut account new --extra-entropy - --keyfile keystore/dave_entropy_stdin.key --password ''
echo "entropy" > entropy.bin
aut account new --extra-entropy entropy.bin --keyfile keystore/dave_entropy_file.key --password ''

# Create account with default keyfile name
aut account new --extra-entropy entropy.bin --keystore test_keystore --password ''
[ "2" == `ls test_keystore | wc -l` ]

# Make a fake transaction and test signing using the new key
aut tx make --keyfile keystore/dave.key --to 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf --value '0.001kwei' --gas 1000 > test.tx
aut account signtx --password '' --keyfile keystore/dave.key test.tx > test.signed.tx

# Sign and verify a message
aut account sign-message --password '' --keyfile keystore/dave.key "A message to be signed" message.sig
aut account verify-signature --keyfile keystore/dave.key "A message to be signed" message.sig
!(aut account verify-signature --keyfile keystore/dave.key "A different message" message.sig)

# Help text
aut account balance --help > /dev/null
aut account import-private-key --help > /dev/null
aut account info --help > /dev/null
aut account list --help > /dev/null
aut account lntn-balances --help > /dev/null
aut account new --help > /dev/null
aut account sign-message --help > /dev/null
aut account signtx --help > /dev/null
aut account verify-signature --help > /dev/null
aut account verify-signature --help > /dev/null

popd

set +e
set +x
