#!/usr/bin/env bash

set -x
set -e

mkdir -p _test_contract_cli
pushd _test_contract_cli

../scripts/setup_config_file.sh

AUTONITY_ADDRESS=$(aut protocol contract-address)
AUTONITY_ABI="$(pip show autonity | grep ^Location: | awk '{print $2}')/autonity/abi/Autonity.abi"

ALICE=0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf
BOB=0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF

# Trivial contract call to Autonity.totalSupply
aut contract call \
    --address ${AUTONITY_ADDRESS} \
    --abi "${AUTONITY_ABI}" \
    totalSupply

# Manual call to Autonity.getValidators to get first validator
aut contract call \
    --address ${AUTONITY_ADDRESS} \
    --abi "${AUTONITY_ABI}" \
    getValidators | jq -r '.[0]' > validator0

# Get the id of the validator and check it matches
CONTRACT_ADDRESS=${AUTONITY_ADDRESS} CONTRACT_ABI="${AUTONITY_ABI}" \
    aut contract call \
    getValidator `cat validator0` > validator0.json

validator0_id=`jq -r '.nodeAddress' validator0.json`

[ `cat validator0` == ${validator0_id} ]

# Alice grants bob the right to spend 10 NTN
aut contract tx \
    --address ${AUTONITY_ADDRESS} \
    --abi "${AUTONITY_ABI}" \
    --from ${ALICE} \
    approve ${BOB} 10_000_000_000_000_000_000

# Alice deploys a dummy contract with 4 parameters
aut contract deploy \
    --contract ../tests/data/token_contract.json \
    ${ALICE} 10000000000000000000 "Test Token" "TST"

popd  # _test_contract_cli
