#!/usr/bin/env bash

set -x
set -e

mkdir -p _test_protocol_cli
pushd _test_protocol_cli

../scripts/setup_config_file.sh

echo "aut protocol config"
aut protocol config

echo "aut protocol deployer"
aut protocol deployer

echo "aut protocol epoch-id"
aut protocol epoch-id

echo "aut protocol epoch-reward"
aut protocol epoch-reward

echo "aut protocol epoch-total-bonded-stake"
aut protocol epoch-total-bonded-stake

echo "aut protocol get-committee"
aut protocol get-committee

echo "aut protocol get-committee-enodes"
aut protocol get-committee-enodes

echo "aut protocol get-last-epoch-block"
aut protocol get-last-epoch-block

echo "aut protocol get-max-committee-size"
aut protocol get-max-committee-size

echo "aut protocol get-minimum-base-fee"
aut protocol get-minimum-base-fee

echo "aut protocol get-operator"
aut protocol get-operator

echo "aut protocol get-proposer"
aut protocol get-proposer 100 3

echo "aut protocol get-validators"
aut protocol get-validators

echo "aut protocol get-version"
aut protocol get-version

echo "aut protocol last-epoch-block"
aut protocol last-epoch-block

echo "aut protocol atn-total-redistributed"
aut protocol atn-total-redistributed

# Test help text (does some parameter validation)
aut protocol config --help > /dev/null
aut protocol deployer --help > /dev/null
aut protocol epoch-id --help > /dev/null
aut protocol epoch-reward --help > /dev/null
aut protocol epoch-total-bonded-stake --help > /dev/null
aut protocol get-committee --help > /dev/null
aut protocol get-committee-enodes --help > /dev/null
aut protocol get-last-epoch-block --help > /dev/null
aut protocol get-max-committee-size --help > /dev/null
aut protocol get-minimum-base-fee --help > /dev/null
aut protocol get-operator --help > /dev/null
aut protocol get-proposer --help > /dev/null
aut protocol get-validators --help > /dev/null
aut protocol get-version --help > /dev/null
aut protocol last-epoch-block --help > /dev/null
aut protocol total-redistributed --help > /dev/null

set +e
set +x

popd
