#!/usr/bin/env bash

set -x
set -e

mkdir -p _test_contract_cli
pushd _test_contract_cli

../scripts/setup_config_file.sh

AUTONITY_ADDRESS="0xBd770416a3345F91E4B34576cb804a576fa48EB1"
AUTONITY_ABI=../external/autonity.py/autonity/abi/Autonity.abi
ALICE=0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf
BOB=0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF

# Manual call to Autonity.getValidators to get first validator
aut contract call \
    --address ${AUTONITY_ADDRESS} \
    --abi ${AUTONITY_ABI} \
    getValidators | jq -r '.[0]' > validator0

# Get the id of the validator and check it matches
CONTRACT_ADDRESS=${AUTONITY_ADDRESS} CONTRACT_ABI=${AUTONITY_ABI} \
    aut contract call \
    getValidator `cat validator0` | jq -r '.[1]' > validator0.id

[ `cat validator0` == `cat validator0.id` ]

# Alice grants bob the right to spend 10 NTN
aut contract tx \
    --address ${AUTONITY_ADDRESS} \
    --abi ${AUTONITY_ABI} \
    --from ${ALICE} \
    approve ${BOB} 10_000_000_000_000_000_000

popd  # _test_contract_cli
