#!/usr/bin/env bash

set -x
set -e

mkdir -p _test_token_cli
pushd _test_token_cli

../scripts/setup_config_file.sh

# We use these dummy Dummy keys:
ALICE=0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf
BOB=0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF

# Find the address of the first validators Liquid Newton contract.
aut validator list > validators
v1=$(head -n1 validators)

treasury=`aut validator info --validator ${v1} | jq -r '.treasury'`
token=`aut validator info --validator ${v1} | jq -r '.liquid_contract'`

# Queries

aut token name --token ${token} || echo -n
aut token symbol --token ${token} || echo -n
aut token decimals --token ${token}
aut token total-supply --token ${token}
aut token balance-of --token ${token} ${treasury}
aut token allowance --token ${token} ${treasury}

# "treasury" transfers 1 LNTN token to ALICE (should succeed)
aut token transfer --token ${token} --from ${treasury} ${ALICE} 0.000000000000000001 > transfer.tx
# "treasury" grants ALICE permission to spend 10 of his tokens.
aut token approve --token ${token} --from ${treasury} ${ALICE} 10 > approve.tx
# ALICE sends 10 of "treasury"'s tokens to BOB  (use --gas flag to prevent simulation on node)
aut token transfer-from --gas 1000000 --token ${token} --from ${ALICE} ${treasury} ${BOB} 10 > transfer_from.tx

# Help text
aut token name --help > /dev/null
aut token symbol --help > /dev/null
aut token decimals --help > /dev/null
aut token total-supply --help > /dev/null
aut token balance-of --help > /dev/null
aut token allowance --help > /dev/null
aut token transfer --help > /dev/null
aut token approve --help > /dev/null
aut token transfer-from --help > /dev/null

popd  # _test_token_cli
