"""
Code that is executed when 'aut sendtx..' is invoked on the command-line.
"""

from autcli.options import rpc_endpoint_option
from autcli.utils import load_from_file_or_stdin, web3_from_endpoint_arg

from autonity.utils.tx import send_tx

import json
from web3 import Web3
from eth_account.account import SignedTransaction
from click import command, argument
from typing import Optional


@command()
@rpc_endpoint_option
@argument("tx-file")
def sendtx(rpc_endpoint: Optional[str], tx_file: str) -> None:
    """
    Send raw transaction (as generated by signtx) contained in the
    given file.  Use '-' to read from stdin instead of a file.
    Outputs the transaction hash if it is successfully sent.
    """

    signed_tx = SignedTransaction(**json.loads(load_from_file_or_stdin(tx_file)))
    w3 = web3_from_endpoint_arg(None, rpc_endpoint)
    tx_hash = send_tx(w3, signed_tx)
    print(Web3.toHex(tx_hash))
