"""
Code that is executed when 'aut sendtx..' is invoked on the command-line.
"""

from autcli.config import get_rpc_endpoint
from autcli.utils import load_from_file_or_stdin, web3_from_endpoint_arg

from autonity.utils.tx import send_tx

import json
from web3 import Web3
from eth_account.account import SignedTransaction
from click import command, option, argument


@command()
@option("--rpc-endpoint", "-r", help="RPC endpoint (defaults to WEB3_ENDPOINT env var")
@argument("tx-file")
def sendtx(tx_file: str, rpc_endpoint: str) -> None:
    """
    Send raw transaction (as generated by signtx) contained in the
    given file.  Use '-' to read from stdin instead of a file.
    Outputs the transaction hash if it is successfully sent.
    """

    signed_tx = SignedTransaction(**json.loads(load_from_file_or_stdin(tx_file)))
    w3 = web3_from_endpoint_arg(get_rpc_endpoint(rpc_endpoint))
    tx_hash = send_tx(w3, signed_tx)
    print(Web3.toHex(tx_hash))
